steps:
- id: npm-ci
  name: node:12
  secretEnv: ['NPM_TOKEN']
  entrypoint: npm
  args: ['i', '--quiet']

- id: npm-publish
  name: 'gcr.io/$PROJECT_ID/cloudbuilders/npm:6.13.4'
  secretEnv: ['NPM_TOKEN']
  env:
  - 'TAG_NAME=$TAG_NAME'
  - '_PR_NUMBER=$_PR_NUMBER'

timeout: 10m

logsBucket: 'gs://$PROJECT_ID-cloudbuild-logs'

tags:
- 'backend'
- 'npm'
- 'nodejs'

secrets:
- kmsKeyName: projects/production-197117/locations/global/keyRings/gcb/cryptoKeys/main
  secretEnv:
    NPM_TOKEN: 'CiQA/4lqmakm1M7hB24kv4Fztrvz8xz+yy1xQo3wY7gQrDdMicISTQC7Kyfr3ULFlWV044QfWdySrryle6UDwjdzuo/TBDkNwX8AVH5DNbszvTEqTlzIb/V4l9jd3ZDV1gXo44fkP5OyVV2oIwLF9lO53rk6'
